version: "3.8"

services:
  production:
    build:
      context: .
      target: production
    environment:
      - "ADMINS"
      - "ADMIN_SECRET"
      - "BRAND"
      - "COPYRIGHT_AUTHOR"
      - "COPYRIGHT_EMAIL"
      - "CSP_REPORT_ONLY"
      - "DATABASE_URL"
      - "DEFAULT_MAIL_SENDER"
      - "HEROKU_DATABASE_URL"
      - "LOGDNA_KEY"
      - "LOG_LEVEL"
      - "MAIL_DEFAULT_SENDER"
      - "MAIL_PASSWORD"
      - "MAIL_PORT"
      - "MAIL_SERVER"
      - "MAIL_SUBJECT_PREFIX"
      - "MAIL_USERNAME"
      - "NAVBAR_HOME"
      - "NAVBAR_ICONS"
      - "NAVBAR_USER_DROPDOWN"
      - "PYTHON_RUNTIME_VERSION"
      - "REDIS_TLS_URL"
      - "REDIS_URL"
      - "RESERVED_USERNAMES"
      - "SECRET_KEY"
      - "SEND_FILE_MAX_AGE_DEFAULT"
    expose:
      - 5000
    image: jss-production:1.17.0
    volumes:
      - static_volume:/home/jss/app/static/

  development:
    build:
      context: .
      target: development
    command: ./.venv/bin/flask run --host 0.0.0.0
    depends_on:
      - postgres
      - redis
    environment:
      - "BRAND"
      - "COPYRIGHT_AUTHOR"
      - "COPYRIGHT_EMAIL"
      - "DATABASE=postgres"
      - "DATABASE_URL=postgresql://jss:jss@postgres:5432/jss"
      - "MAIL_PASSWORD=${DEV_MAIL_PASSWORD}"
      - "MAIL_PORT=${DEV_MAIL_PORT}"
      - "MAIL_SERVER=${DEV_MAIL_SERVER}"
      - "MAIL_SUBJECT_PREFIX"
      - "MAIL_USERNAME=${DEV_MAIL_USERNAME}"
      - "MAIL_USE_SSL=${DEV_MAIL_USE_SSL}"
      - "MAIL_USE_TLS=${DEV_MAIL_USE_TLS}"
      - "REDIS_URL=redis://redis:6379/0"
      - "SIGNATURE"
      - "SQL_HOST=postgres"
      - "SQL_PORT=5432"
    image: jss-development:1.17.0
    ports:
      - "5000:5000"
    volumes:
      - ./app:/home/jss/app
      - ./migrations:/home/jss/migrations

  postgres:
    environment:
      POSTGRES_USER: jss
      POSTGRES_PASSWORD: jss
      POSTGRES_DB: jss
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build:
      context: .
      target: nginx
    depends_on:
      - production
    image: jss-nginx:1.17.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/jss/app/static/

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis_dump:/data/

volumes:
  postgres_data:
  redis_dump:
  static_volume:
