"""Adds versioning for `Post`

Revision ID: 0fbbcf5eb614
Revises: d30fd601c9b3
Create Date: 2021-10-04 01:11:09.057392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbbcf5eb614'
down_revision = 'd30fd601c9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), autoincrement=False, nullable=True),
    sa.Column('body', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('edited', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_post_version_created'), 'post_version', ['created'], unique=False)
    op.create_index(op.f('ix_post_version_end_transaction_id'), 'post_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_post_version_operation_type'), 'post_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_post_version_transaction_id'), 'post_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('edited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'edited')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_post_version_transaction_id'), table_name='post_version')
    op.drop_index(op.f('ix_post_version_operation_type'), table_name='post_version')
    op.drop_index(op.f('ix_post_version_end_transaction_id'), table_name='post_version')
    op.drop_index(op.f('ix_post_version_created'), table_name='post_version')
    op.drop_table('post_version')
    # ### end Alembic commands ###
