"""adds confirmation fields to `User`

Revision ID: 5502155cc0c0
Revises: 50587486df14
Create Date: 2021-10-01 23:37:25.022286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5502155cc0c0'
down_revision = '50587486df14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_confirmed_on', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_confirmed_on', 'user', ['confirmed_on'], unique=False)
    # ### end Alembic commands ###
