"""Adds versioning `User.authorized`

Revision ID: ee3c6c0702a6
Revises: 0fbbcf5eb614
Create Date: 2021-10-04 03:41:16.571947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3c6c0702a6'
down_revision = '0fbbcf5eb614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authorized')
    # ### end Alembic commands ###
