"""Adds `language` to `Post`

Revision ID: fb14f086a017
Revises: 61a01b56cb45
Create Date: 2022-06-02 23:13:27.271181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb14f086a017'
down_revision = '61a01b56cb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    op.add_column('post_version', sa.Column('language', sa.String(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_version', 'language')
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
