name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: >
      ${{ matrix.os }}
      -python${{ matrix.python-version }}
      -node@${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.8"
        node-version:
          - 16.x.x
        os:
          - ubuntu-latest
    steps:
      - name: Checkout build
        id: checkout-build
        uses: actions/checkout@v4
      - name: Install Poetry
        id: install-poetry
        run: pipx install poetry
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Python Packages
        id: install-python-packages
        run: poetry install
      - name: Install Node Packages
        id: install-node-packages
        run: npm install
      - name: Audit
        id: audit
        run: npm run audit
      - name: Build
        id: build
        run: npm run webpack:prod
      - name: Docker
        id: docker
        run: docker compose build
      - name: Upload coverage
        id: upload-coverage
        uses: codecov/codecov-action@v3
      - name: Build docs
        id: build-docs
        run: poetry run sphinx-build -M html docs docs/_build -W
      - name: Deploy docs
        id: deploy-docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
