name: ci

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  ci:
    name: ${{ matrix.os }}-python${{ matrix.python-version }}-node@${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    env:
      PYAUD_GH_NAME: jshwi
      PYAUD_GH_EMAIL: stephen@jshwisolutions.com
      PYAUD_GH_TOKEN: ${{ secrets.PYAUD_GH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECOV_SLUG: jshwi/jss

    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
        node-version: [16.x.x]

    steps:
      - name: Checkout build
        id: checkout-build
        uses: actions/checkout@v2

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip pipenv==2021.5.29 wheel

      - name: Cache Pipenv
        uses: actions/cache@v2
        id: pipenv-cache
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pip-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: ${{ runner.os }}-pipenv-

      - name: Cache npm
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Setup pipenv
        id: setup-pipenv
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Setup Node
        id: setup-node
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts

      - name: Audit
        id: audit
        run: |
          npm run audit
