name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }}-python${{ matrix.python-version }}-node@${{ matrix.node-version }}
    runs-on: ubuntu-18.04
    env:
      PYAUD_GH_NAME: jshwi
      PYAUD_GH_EMAIL: stephen@jshwisolutions.com
      PYAUD_GH_TOKEN: ${{ secrets.PYAUD_GH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECOV_SLUG: jshwi/jss

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        node-version: [16.x.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update Apt
        run: sudo apt-get update -y && sudo apt-get install zstd -y

      - name: Install Pipenv
        run: python -m pip install --upgrade pip pipenv==2021.5.29 wheel

      - name: Cache Pipenv
        uses: actions/cache@v2
        id: pipenv-cache
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: ${{ runner.os }}-pipenv-

      - name: Cache npm
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Setup Pip
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        run: pipenv install --dev

      - name: Setup Node
        run: npm ci --ignore-scripts

      - name: Audit
        run: npm run audit
